version: '2'
volumes:
  postgis-data:

services:
  db:
    image: kartoza/postgis:10.0-2.4
    volumes:
      - 'postgis-data:/var/lib/postgresql'
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5432:5432
    restart: unless-stopped
