"""empty message

Revision ID: d8729c81b291
Revises: 
Create Date: 2018-07-14 14:59:26.616128

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = 'd8729c81b291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='LINESTRING', srid=4326), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_cell_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcc', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('radio', sa.String(), nullable=False),
    sa.Column('cell', sa.Integer(), nullable=False),
    sa.Column('net', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('range', sa.Integer(), nullable=False),
    sa.Column('averageSignal', sa.Integer(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('changeable', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('coord', Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_cell_id')
    op.drop_table('mapping')
    # ### end Alembic commands ###
